# Generated by Django 4.2.3 on 2023-07-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=20)),
                ('Gender', models.CharField(max_length=8)),
                ('Section', models.CharField(max_length=10)),
                ('Roll_Number', models.IntegerField(max_length=10)),
                ('Address', models.TextField(max_length=50)),
                ('Phone', models.IntegerField(max_length=20)),
            ],
        ),
    ]
